<!doctype html>
<html>
<head>
<title>insertion form</title>
</head>
<body bgcolor=sky_blue>
<center>
<h1 style="color:blue;text-transform:capitalize;"> book record managment</h1>
<form action="insertion.php" method="post">
<table>
<tr>
<th>title</th>
<td><input type="text" name="title" required/></td>
</tr>
<tr>
<th>price</th>
<td><input type="text" name="price" required/></td>
</tr>
<tr>
<th>author</th>
<td><input type="text" name="author"/></td>
</tr>
<tr>
<th></th>
<td><input type="submit" value="insert"/></td>
</tr>
</table>
</form>
</center>
</body>
</html>