<html>
<head>
<title>IP COLLEGE FORM</title>
</head>
<body bgcolor="red">
<h1 align="center">ADDMISSION FORM</H1>
<center><img src="sky.jpg" height="50%" width="50%"></center><hr>
<center>
<form action="insert.PHP" method="get">
<table>
<tr>
<td>Name</td>
<td><input type="text" name="Name" required/></td>
</tr>
<tr>
<td>Father_Name</td>
<td><input type="text" name="Father_Name" required/></td>
</tr>
<tr>
<td>Gender</td>
<td><input type="radio" name="Gender"/>m
<input type="radio" name="Gender"/>f
<input type="radio" name="Gender"/>other</td>
</tr>
<tr>
<td>ECA</td>
<td><input type="checkbox" name="NCC"/>NCC
<input type="checkbox" name="NSS"/>NSS
<input type="checkbox" name="scots"/>scots</td>
</tr>
<tr>
<td>City</td>
<td><select>
<option>bhopal</option>
<option>goa</option>
<option>up</option>
<option>delhi</option>
<option>kanpur</option>
<option>hisar</option>
<option>hapur</option>
<option>mp</option>
<option>andhara</option>
</select></td>
</tr>

<tr>
<center><td><input type ="reset" value="Reset"/>
        <input type="submit" value="insert"></td></center>
</tr>
</table>
<h1>click here to go back</h1>
<a href="aiactr.html">Click</a>
</center>
</form>
</body>
</html>